a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('É uma número? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumérico? '), a.isalnum()
print('Está em maiusculas? ', a.isupper())
print('Ésta em minúsculas? ', a.islower())
print('Ésta capitalizada? ', a.istitle())

